import React from "react";
import Head from "next/head";
import Image from 'next/image'

export const Header = () => {


return(
<>
<Head>
        <title>This is your funny Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>

<main>
<div className="header">
<h2 className="title"> My joke page </h2>
<Image src='/img/lol.png'
width={50} height={50}/>
</div>

</main>
</div>

</>
)

}